### ISSUE TITLE
NSLogScale buggy for domain starting at 0

### ISSUE THREAD

**Issue by NicolasAnquetil** [ObjectProfile/NumericScales#1]
```| log |
log := NSLogScale new
	domain: #(1 100).
self assert: (log scale: 1) equals: 0.
self assert: (log scale: 10) equals: 0.5.
self assert: (log scale: 100) equals: 1.
```
Now change the domain to `#(0 100)` and `#scale:` returns NaN...
Am I missing something ?

**Comment by bergel** [comment]
a scale maps a `domain` to a `range`. But the `domain` must be meaningful when being mapped. if 0 is in the domain, then it cannot be mapped. It is not really a bug. But this is true that the documentation can be better

**Comment by NicolasAnquetil** [comment]
I don't see why.
The domain is whatever I would like it to be, no ?
For example, for linear, we could have a domain from $a to $z (of course, for log it is less clear what it would mean).
So why can't I say that my numbers go from 0 to 100 and I want the progression to follow a log curve ?
Or they go from -10 to 10 and I want to follow a square root curve ?
Thus the "user domain" would be mapped to an internal valid domain for the chosen "function" (e.g. from 1 to 100 for log, from 0 to 100 for square root), and NSScale would do its magic

Don't you agree ?

**Comment by akevalion** [comment]
Internally NSLogScale uses `ln` (natural log). the result of `0 ln` in pharo is infinite.
But many articles says its undefined http://www.mclph.umn.edu/mathrefresh/logs3.html#:~:text=2.-,log%200%20is%20undefined.,3.

If you still want to use a log scale that includes zero in the domain. please try
```st
log := NSSymLogScale new
	domain: { 0. 100 }.
log scale: 0. "0.0"
```
