### ISSUE TITLE
Cleanups and own package for GT

### ISSUE THREAD

**Issue by astares** [ObjectProfile/NumericScales#2]
- NSAbstractInterpolator should return true for isAbstract
- GT extensions should be in an own package (to not have them in Pharo 10)

![image](https://user-images.githubusercontent.com/5980033/142270799-e616f1b3-16dd-4f2b-949d-d6a4059c5cba.png)

and other cleanups

**Comment by akevalion** [comment]
this is completed

**Comment by astares** [comment]
Great, thanks!
